name: Deploy to Vercel Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build
        env:
          PUBLIC_SUPABASE_URL: ${{ secrets.PUBLIC_SUPABASE_URL }}
          PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PUBLIC_SUPABASE_ANON_KEY }}
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Deploy to Vercel
        run: |
          echo "Deploying to Vercel..."
          npx vercel --prod --force --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Comment deployment URL
        uses: actions/github-script@v7
        if: github.event_name == 'workflow_dispatch'
        with:
          script: |
            const deploymentUrl = process.env.VERCEL_URL || 'Deployment URL not available';
            console.log(`🚀 Deployment completed!`);
            console.log(`📍 URL: ${deploymentUrl}`);
            console.log(`🔒 Password protection: ${process.env.VERCEL_PASSWORD ? 'Enabled' : 'Disabled'}`);