name: Link Vercel Project

on:
  workflow_dispatch:

jobs:
  link:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: Link Project
        run: |
          echo "Linking project..."
          npx vercel link --token ${{ secrets.VERCEL_TOKEN }} --yes
          echo "Project linked successfully"
          
      - name: Get Project Info
        run: |
          echo "Getting project information..."
          if [ -f .vercel/project.json ]; then
            echo "Project JSON contents:"
            cat .vercel/project.json
          else
            echo "No .vercel/project.json found"
          fi